"""add_performance_indexes_phase1

Revision ID: 67525c3297b2
Revises: 6bb2f32fe517
Create Date: 2026-01-02 07:49:31.336162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67525c3297b2'
down_revision: Union[str, None] = '6bb2f32fe517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CRITICAL: Convert JSON columns from text to jsonb if needed
    # This handles the SQLite->PostgreSQL migration where JSON was stored as text
    # The USING clause safely converts text JSON to native jsonb
    connection = op.get_bind()

    # Check if we're on PostgreSQL (migrations should be PostgreSQL-only in production)
    if connection.dialect.name == 'postgresql':
        # Convert text columns to jsonb if they exist and are text type
        # This is idempotent - if already jsonb, ALTER TYPE will be a no-op
        op.execute("""
            DO $$
            BEGIN
                -- Convert designers column to jsonb
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'boardgames'
                    AND column_name = 'designers'
                    AND data_type = 'text'
                ) THEN
                    ALTER TABLE boardgames
                    ALTER COLUMN designers TYPE jsonb USING designers::jsonb;
                END IF;

                -- Convert publishers column to jsonb
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'boardgames'
                    AND column_name = 'publishers'
                    AND data_type = 'text'
                ) THEN
                    ALTER TABLE boardgames
                    ALTER COLUMN publishers TYPE jsonb USING publishers::jsonb;
                END IF;

                -- Convert mechanics column to jsonb
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'boardgames'
                    AND column_name = 'mechanics'
                    AND data_type = 'text'
                ) THEN
                    ALTER TABLE boardgames
                    ALTER COLUMN mechanics TYPE jsonb USING mechanics::jsonb;
                END IF;

                -- Convert artists column to jsonb
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'boardgames'
                    AND column_name = 'artists'
                    AND data_type = 'text'
                ) THEN
                    ALTER TABLE boardgames
                    ALTER COLUMN artists TYPE jsonb USING artists::jsonb;
                END IF;
            END $$;
        """)

    # Now create the indexes (after ensuring columns are jsonb)
    op.create_index('idx_category_rating_date', 'boardgames', ['mana_meeple_category', 'average_rating', 'date_added'], unique=False, postgresql_where=sa.text("status = 'OWNED'"))
    op.create_index('idx_designers_gin', 'boardgames', ['designers'], unique=False, postgresql_using='gin', postgresql_ops={'designers': 'jsonb_path_ops'})
    op.create_index('idx_mechanics_gin', 'boardgames', ['mechanics'], unique=False, postgresql_using='gin', postgresql_ops={'mechanics': 'jsonb_path_ops'})
    op.create_index('idx_public_games_covering', 'boardgames', ['status', 'is_expansion', 'expansion_type', 'mana_meeple_category'], unique=False, postgresql_include=['title', 'year', 'players_min', 'players_max', 'average_rating', 'thumbnail_url', 'image'])
    op.create_index('idx_status_date_nz', 'boardgames', ['status', 'date_added', 'nz_designer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_status_date_nz', table_name='boardgames')
    op.drop_index('idx_public_games_covering', table_name='boardgames', postgresql_include=['title', 'year', 'players_min', 'players_max', 'average_rating', 'thumbnail_url', 'image'])
    op.drop_index('idx_mechanics_gin', table_name='boardgames', postgresql_using='gin', postgresql_ops={'mechanics': 'jsonb_path_ops'})
    op.drop_index('idx_designers_gin', table_name='boardgames', postgresql_using='gin', postgresql_ops={'designers': 'jsonb_path_ops'})
    op.drop_index('idx_category_rating_date', table_name='boardgames', postgresql_where=sa.text("status = 'OWNED'"))
    # ### end Alembic commands ###
