"""Initial schema baseline

Revision ID: a879cc066239
Revises: 
Create Date: 2025-12-28 17:53:27.477999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a879cc066239'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardgames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('categories', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('players_min', sa.Integer(), nullable=True),
    sa.Column('players_max', sa.Integer(), nullable=True),
    sa.Column('playtime_min', sa.Integer(), nullable=True),
    sa.Column('playtime_max', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('bgg_id', sa.Integer(), nullable=True),
    sa.Column('thumbnail_file', sa.String(length=256), nullable=True),
    sa.Column('mana_meeple_category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('designers', sa.JSON(), nullable=True),
    sa.Column('publishers', sa.JSON(), nullable=True),
    sa.Column('mechanics', sa.JSON(), nullable=True),
    sa.Column('artists', sa.JSON(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('complexity', sa.Float(), nullable=True),
    sa.Column('bgg_rank', sa.Integer(), nullable=True),
    sa.Column('users_rated', sa.Integer(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=True),
    sa.Column('is_cooperative', sa.Boolean(), nullable=True),
    sa.Column('nz_designer', sa.Boolean(), nullable=True),
    sa.Column('game_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('has_sleeves', sa.String(length=20), nullable=True),
    sa.Column('is_sleeved', sa.Boolean(), nullable=True),
    sa.Column('aftergame_game_id', sa.String(length=36), nullable=True),
    sa.Column('is_expansion', sa.Boolean(), nullable=False),
    sa.Column('base_game_id', sa.Integer(), nullable=True),
    sa.Column('expansion_type', sa.String(length=50), nullable=True),
    sa.Column('modifies_players_min', sa.Integer(), nullable=True),
    sa.Column('modifies_players_max', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IS NULL OR status IN ('OWNED', 'BUY_LIST', 'WISHLIST')", name='valid_status'),
    sa.CheckConstraint('average_rating IS NULL OR (average_rating >= 0 AND average_rating <= 10)', name='valid_rating'),
    sa.CheckConstraint('complexity IS NULL OR (complexity >= 1 AND complexity <= 5)', name='valid_complexity'),
    sa.CheckConstraint('min_age IS NULL OR (min_age >= 0 AND min_age <= 100)', name='valid_min_age'),
    sa.CheckConstraint('players_max IS NULL OR players_min IS NULL OR players_max >= players_min', name='players_max_gte_min'),
    sa.CheckConstraint('players_min IS NULL OR players_min >= 1', name='valid_min_players'),
    sa.CheckConstraint('playtime_max IS NULL OR playtime_min IS NULL OR playtime_max >= playtime_min', name='playtime_max_gte_min'),
    sa.CheckConstraint('playtime_min IS NULL OR playtime_min > 0', name='valid_playtime_min'),
    sa.CheckConstraint('year IS NULL OR (year >= 1900 AND year <= 2100)', name='valid_year'),
    sa.ForeignKeyConstraint(['base_game_id'], ['boardgames.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_year_rating', 'boardgames', ['mana_meeple_category', 'year', 'average_rating'], unique=False, postgresql_where=sa.text("status = 'OWNED'"))
    op.create_index('idx_created_category', 'boardgames', ['created_at', 'mana_meeple_category'], unique=False)
    op.create_index('idx_date_added_status', 'boardgames', ['date_added', 'status'], unique=False, postgresql_where=sa.text("status = 'OWNED'"))
    op.create_index('idx_expansion_lookup', 'boardgames', ['is_expansion', 'base_game_id'], unique=False)
    op.create_index('idx_nz_designer_category', 'boardgames', ['nz_designer', 'mana_meeple_category'], unique=False, postgresql_where=sa.text('nz_designer = 1'))
    op.create_index('idx_player_range', 'boardgames', ['players_min', 'players_max'], unique=False, postgresql_where=sa.text("status = 'OWNED'"))
    op.create_index('idx_players_playtime', 'boardgames', ['players_min', 'players_max', 'playtime_min', 'playtime_max'], unique=False)
    op.create_index('idx_rating_rank', 'boardgames', ['average_rating', 'bgg_rank'], unique=False)
    op.create_index('idx_year_category', 'boardgames', ['year', 'mana_meeple_category'], unique=False)
    op.create_index(op.f('ix_boardgames_aftergame_game_id'), 'boardgames', ['aftergame_game_id'], unique=False)
    op.create_index(op.f('ix_boardgames_base_game_id'), 'boardgames', ['base_game_id'], unique=False)
    op.create_index(op.f('ix_boardgames_bgg_id'), 'boardgames', ['bgg_id'], unique=True)
    op.create_index(op.f('ix_boardgames_date_added'), 'boardgames', ['date_added'], unique=False)
    op.create_index(op.f('ix_boardgames_game_type'), 'boardgames', ['game_type'], unique=False)
    op.create_index(op.f('ix_boardgames_is_expansion'), 'boardgames', ['is_expansion'], unique=False)
    op.create_index(op.f('ix_boardgames_mana_meeple_category'), 'boardgames', ['mana_meeple_category'], unique=False)
    op.create_index(op.f('ix_boardgames_nz_designer'), 'boardgames', ['nz_designer'], unique=False)
    op.create_index(op.f('ix_boardgames_status'), 'boardgames', ['status'], unique=False)
    op.create_index(op.f('ix_boardgames_title'), 'boardgames', ['title'], unique=False)
    op.create_table('background_task_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=200), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_failure_game', 'background_task_failures', ['game_id', 'task_type'], unique=False)
    op.create_index('idx_task_failure_resolved', 'background_task_failures', ['resolved', 'created_at'], unique=False)
    op.create_index('idx_task_failure_type_date', 'background_task_failures', ['task_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_background_task_failures_created_at'), 'background_task_failures', ['created_at'], unique=False)
    op.create_index(op.f('ix_background_task_failures_game_id'), 'background_task_failures', ['game_id'], unique=False)
    op.create_index(op.f('ix_background_task_failures_resolved'), 'background_task_failures', ['resolved'], unique=False)
    op.create_index(op.f('ix_background_task_failures_task_type'), 'background_task_failures', ['task_type'], unique=False)
    op.create_table('buy_list_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('bgo_link', sa.Text(), nullable=True),
    sa.Column('lpg_rrp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lpg_status', sa.String(length=50), nullable=True),
    sa.Column('on_buy_list', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buy_list_rank', 'buy_list_games', ['on_buy_list', 'rank'], unique=False)
    op.create_index('idx_buy_list_status', 'buy_list_games', ['lpg_status', 'on_buy_list'], unique=False)
    op.create_index(op.f('ix_buy_list_games_game_id'), 'buy_list_games', ['game_id'], unique=True)
    op.create_index(op.f('ix_buy_list_games_lpg_status'), 'buy_list_games', ['lpg_status'], unique=False)
    op.create_index(op.f('ix_buy_list_games_on_buy_list'), 'buy_list_games', ['on_buy_list'], unique=False)
    op.create_index(op.f('ix_buy_list_games_rank'), 'buy_list_games', ['rank'], unique=False)
    op.create_table('price_offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('store', sa.Text(), nullable=True),
    sa.Column('price_nzd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('availability', sa.Text(), nullable=True),
    sa.Column('store_link', sa.Text(), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_offer_game_date', 'price_offers', ['game_id', 'checked_at'], unique=False)
    op.create_index('idx_price_offer_store', 'price_offers', ['store', 'in_stock'], unique=False)
    op.create_index(op.f('ix_price_offers_checked_at'), 'price_offers', ['checked_at'], unique=False)
    op.create_index(op.f('ix_price_offers_game_id'), 'price_offers', ['game_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mean_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('best_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('best_store', sa.Text(), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('disc_mean_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('delta', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_snapshot_best', 'price_snapshots', ['best_price', 'discount_pct'], unique=False)
    op.create_index('idx_price_snapshot_game_date', 'price_snapshots', ['game_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_checked_at'), 'price_snapshots', ['checked_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_game_id'), 'price_snapshots', ['game_id'], unique=False)
    op.create_table('sleeves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=200), nullable=True),
    sa.Column('width_mm', sa.Integer(), nullable=False),
    sa.Column('height_mm', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['boardgames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sleeve_game', 'sleeves', ['game_id'], unique=False)
    op.create_index('idx_sleeve_size', 'sleeves', ['width_mm', 'height_mm'], unique=False)
    op.create_index(op.f('ix_sleeves_game_id'), 'sleeves', ['game_id'], unique=False)
    op.create_index(op.f('ix_sleeves_id'), 'sleeves', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sleeves_id'), table_name='sleeves')
    op.drop_index(op.f('ix_sleeves_game_id'), table_name='sleeves')
    op.drop_index('idx_sleeve_size', table_name='sleeves')
    op.drop_index('idx_sleeve_game', table_name='sleeves')
    op.drop_table('sleeves')
    op.drop_index(op.f('ix_price_snapshots_game_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_checked_at'), table_name='price_snapshots')
    op.drop_index('idx_price_snapshot_game_date', table_name='price_snapshots')
    op.drop_index('idx_price_snapshot_best', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_price_offers_game_id'), table_name='price_offers')
    op.drop_index(op.f('ix_price_offers_checked_at'), table_name='price_offers')
    op.drop_index('idx_price_offer_store', table_name='price_offers')
    op.drop_index('idx_price_offer_game_date', table_name='price_offers')
    op.drop_table('price_offers')
    op.drop_index(op.f('ix_buy_list_games_rank'), table_name='buy_list_games')
    op.drop_index(op.f('ix_buy_list_games_on_buy_list'), table_name='buy_list_games')
    op.drop_index(op.f('ix_buy_list_games_lpg_status'), table_name='buy_list_games')
    op.drop_index(op.f('ix_buy_list_games_game_id'), table_name='buy_list_games')
    op.drop_index('idx_buy_list_status', table_name='buy_list_games')
    op.drop_index('idx_buy_list_rank', table_name='buy_list_games')
    op.drop_table('buy_list_games')
    op.drop_index(op.f('ix_background_task_failures_task_type'), table_name='background_task_failures')
    op.drop_index(op.f('ix_background_task_failures_resolved'), table_name='background_task_failures')
    op.drop_index(op.f('ix_background_task_failures_game_id'), table_name='background_task_failures')
    op.drop_index(op.f('ix_background_task_failures_created_at'), table_name='background_task_failures')
    op.drop_index('idx_task_failure_type_date', table_name='background_task_failures')
    op.drop_index('idx_task_failure_resolved', table_name='background_task_failures')
    op.drop_index('idx_task_failure_game', table_name='background_task_failures')
    op.drop_table('background_task_failures')
    op.drop_index(op.f('ix_boardgames_title'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_status'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_nz_designer'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_mana_meeple_category'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_is_expansion'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_game_type'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_date_added'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_bgg_id'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_base_game_id'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_aftergame_game_id'), table_name='boardgames')
    op.drop_index('idx_year_category', table_name='boardgames')
    op.drop_index('idx_rating_rank', table_name='boardgames')
    op.drop_index('idx_players_playtime', table_name='boardgames')
    op.drop_index('idx_player_range', table_name='boardgames', postgresql_where=sa.text("status = 'OWNED'"))
    op.drop_index('idx_nz_designer_category', table_name='boardgames', postgresql_where=sa.text('nz_designer = 1'))
    op.drop_index('idx_expansion_lookup', table_name='boardgames')
    op.drop_index('idx_date_added_status', table_name='boardgames', postgresql_where=sa.text("status = 'OWNED'"))
    op.drop_index('idx_created_category', table_name='boardgames')
    op.drop_index('idx_category_year_rating', table_name='boardgames', postgresql_where=sa.text("status = 'OWNED'"))
    op.drop_table('boardgames')
    # ### end Alembic commands ###
