/**
 * Mock data for frontend tests
 * Provides reusable mock objects for games, buy list items, and other entities
 */

export const mockGames = [
  {
    id: 1,
    title: 'Gloomhaven',
    bgg_id: 174430,
    year: 2017,
    players_min: 1,
    players_max: 4,
    playtime_min: 60,
    playtime_max: 120,
    mana_meeple_category: 'CORE_STRATEGY',
    complexity: 3.87,
    average_rating: 8.67,
    status: 'OWNED',
    designers: ['Isaac Childres'],
    mechanics: ['Campaign / Battle Card Driven', 'Cooperative Game', 'Hand Management'],
    publishers: ['Cephalofair Games'],
    description: 'Gloomhaven is a game of Euro-inspired tactical combat in a persistent world of shifting motives.',
    thumbnail_url: 'https://cf.geekdo-images.com/thumb/gloomhaven.jpg',
    image: 'https://cf.geekdo-images.com/original/gloomhaven.jpg',
    nz_designer: false,
    is_cooperative: true,
    min_age: 14,
  },
  {
    id: 2,
    title: 'Wingspan',
    bgg_id: 266192,
    year: 2019,
    players_min: 1,
    players_max: 5,
    playtime_min: 40,
    playtime_max: 70,
    mana_meeple_category: 'GATEWAY_STRATEGY',
    complexity: 2.44,
    average_rating: 8.07,
    status: 'OWNED',
    designers: ['Elizabeth Hargrave'],
    mechanics: ['Hand Management', 'Set Collection', 'Engine Building'],
    publishers: ['Stonemaier Games'],
    description: 'Wingspan is a competitive, medium-weight, card-driven, engine-building board game.',
    thumbnail_url: 'https://cf.geekdo-images.com/thumb/wingspan.jpg',
    image: 'https://cf.geekdo-images.com/original/wingspan.jpg',
    nz_designer: false,
    is_cooperative: false,
    min_age: 10,
  },
  {
    id: 3,
    title: 'Pandemic',
    bgg_id: 30549,
    year: 2008,
    players_min: 2,
    players_max: 4,
    playtime_min: 45,
    playtime_max: 45,
    mana_meeple_category: 'COOP_ADVENTURE',
    complexity: 2.43,
    average_rating: 7.60,
    status: 'OWNED',
    designers: ['Matt Leacock'],
    mechanics: ['Action Points', 'Cooperative Game', 'Point to Point Movement'],
    publishers: ['Z-Man Games'],
    description: 'Your team of experts must prevent the world from succumbing to a viral pandemic.',
    thumbnail_url: 'https://cf.geekdo-images.com/thumb/pandemic.jpg',
    image: 'https://cf.geekdo-images.com/original/pandemic.jpg',
    nz_designer: false,
    is_cooperative: true,
    min_age: 8,
  },
  {
    id: 4,
    title: 'Codenames',
    bgg_id: 178900,
    year: 2015,
    players_min: 2,
    players_max: 8,
    playtime_min: 15,
    playtime_max: 15,
    mana_meeple_category: 'PARTY_ICEBREAKERS',
    complexity: 1.31,
    average_rating: 7.68,
    status: 'OWNED',
    designers: ['Vlaada Chvátil'],
    mechanics: ['Memory', 'Pattern Recognition', 'Team-Based Game'],
    publishers: ['Czech Games Edition'],
    description: 'Two rival spymasters know the secret identities of 25 agents.',
    thumbnail_url: 'https://cf.geekdo-images.com/thumb/codenames.jpg',
    image: 'https://cf.geekdo-images.com/original/codenames.jpg',
    nz_designer: false,
    is_cooperative: false,
    min_age: 14,
  },
  {
    id: 5,
    title: 'Kingdomino',
    bgg_id: 204583,
    year: 2016,
    players_min: 2,
    players_max: 4,
    playtime_min: 15,
    playtime_max: 15,
    mana_meeple_category: 'KIDS_FAMILIES',
    complexity: 1.22,
    average_rating: 7.42,
    status: 'OWNED',
    designers: ['Bruno Cathala'],
    mechanics: ['Tile Placement', 'Drafting', 'Pattern Building'],
    publishers: ['Blue Orange Games'],
    description: 'Build your kingdom and make sure to get the best plots of land.',
    thumbnail_url: 'https://cf.geekdo-images.com/thumb/kingdomino.jpg',
    image: 'https://cf.geekdo-images.com/original/kingdomino.jpg',
    nz_designer: false,
    is_cooperative: false,
    min_age: 8,
  },
];

export const mockBuyListItems = [
  {
    id: 1,
    game_id: 1,
    priority: 1,
    status: 'wishlist',
    price: 89.99,
    notes: 'High priority - popular game',
    game: mockGames[0],
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 2,
    game_id: 2,
    priority: 2,
    status: 'ordered',
    price: 65.00,
    notes: 'Ordered from local supplier',
    game: mockGames[1],
    created_at: '2025-01-05T00:00:00Z',
    updated_at: '2025-01-16T00:00:00Z',
  },
  {
    id: 3,
    game_id: 3,
    priority: 3,
    status: 'purchased',
    price: 45.00,
    notes: 'Arrived and in stock',
    game: mockGames[2],
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-17T00:00:00Z',
  },
];

export const mockPriceSnapshots = [
  {
    id: 1,
    buy_list_item_id: 1,
    price: 89.99,
    store_name: 'Mighty Ape',
    url: 'https://mightyape.co.nz/gloomhaven',
    created_at: '2025-01-15T00:00:00Z',
  },
  {
    id: 2,
    buy_list_item_id: 1,
    price: 95.00,
    store_name: 'Board Game Oracle',
    url: 'https://boardgameoracle.com/gloomhaven',
    created_at: '2025-01-15T01:00:00Z',
  },
  {
    id: 3,
    buy_list_item_id: 2,
    price: 65.00,
    store_name: 'Gamers Guild',
    url: 'https://gamersguild.co.nz/wingspan',
    created_at: '2025-01-16T00:00:00Z',
  },
];

export const mockCategoryCounts = {
  COOP_ADVENTURE: 45,
  CORE_STRATEGY: 78,
  GATEWAY_STRATEGY: 92,
  KIDS_FAMILIES: 34,
  PARTY_ICEBREAKERS: 56,
  uncategorized: 12,
};

export const mockSleeveData = [
  {
    id: 1,
    game_id: 1,
    card_type: 'Standard',
    width_mm: 63.5,
    height_mm: 88,
    quantity: 100,
    notes: 'Main game cards',
  },
  {
    id: 2,
    game_id: 1,
    card_type: 'Mini',
    width_mm: 44,
    height_mm: 67,
    quantity: 50,
    notes: 'Event cards',
  },
];

export const mockExpansions = [
  {
    id: 10,
    title: 'Gloomhaven: Forgotten Circles',
    bgg_id: 239188,
    parent_game_id: 1,
    year: 2019,
    status: 'OWNED',
  },
  {
    id: 11,
    title: 'Gloomhaven: Jaws of the Lion',
    bgg_id: 291457,
    parent_game_id: 1,
    year: 2020,
    status: 'OWNED',
  },
];

export const mockBGGSearchResults = [
  {
    id: 174430,
    name: 'Gloomhaven',
    year: 2017,
    type: 'boardgame',
  },
  {
    id: 266192,
    name: 'Wingspan',
    year: 2019,
    type: 'boardgame',
  },
];

export const mockAdminSession = {
  token: 'mock-jwt-token-12345',
  username: 'admin',
  expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
};

export const mockToastMessages = {
  success: 'Operation completed successfully',
  error: 'An error occurred',
  info: 'Information message',
  warning: 'Warning message',
};
